import './sass/main.scss';
import './js/changeTheme';
import './js/fetchCard';
import './js/fetchAPI';
import './js/navigation';
import './js/loader';
import './js/logoAnime';
import './js/dev-modal';
import './js/pagination';
import './js/btnUp';
// import './js/home';
import './js/openMovieCard';
import './js/renderLibrary';
import './js/registration';
